site_name: DiscordSRVUtils
site_description: The Wiki For How DiscordSRVUtils works and how to set it up
repo_url: https://github.com/BlueDevelopersInc/dsu-wiki
repo_name: Wiki Github
edit_uri: edit/master/docs
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  custom_dir: 'custom_theme'
  features:
    - navigation.expand
  palette:
    - scheme: slate
      primary: light blue
      accent: blue
  
nav:
    - 'Configuration':
      - 'Messages': messages.md 
      - 'Message JSON': message-json.md
    - 'Common Problems': common-problems.md
    - 'Tickets System':
      - 'What are tickets': tickets.md
      - 'How to Make a Ticket Panel': create-panel.md
    - 'Leveling System': 
      - 'How it works': leveling.md
    - 'Suggestions System': 
      - 'How it works': suggestions.md
    - 'Status':
        - 'How to set it up': status.md
    - 'Punishments Integration': punishments-integration.md
    - 'Fixing Problems':
        - 'Request a Feature': 'https://github.com/BlueDevelopersInc/DiscordSRVUtils/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFeature+Request%5D+'
        - 'Report a Bug': 'https://github.com/BlueDevelopersInc/DiscordSRVUtils/issues/new?assignees=&labels=bug&template=bug-report.md&title=%5BBUG%5D'
        - 'Get Support': 'https://discordsrvutils.xyz/support'
    
    
    
extra_css:
  - stylesheets/extra.css


dev_addr: '0.0.0.0:3000'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discordsrvutils.xyz/support
      name: DiscordSRVUtils Support


