site_name: DiscordSRVUtils
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  custom_dir: 'custom_theme'
  features:
    - navigation.expand
  palette:
    - scheme: slate
      primary: light blue
      accent: blue
  
nav:
    - 'Configuration':
      - 'Messages': messages.md 
      - 'Message JSON': message-json.md
    - 'Common Problems': common-problems.md
    - 'Tickets System':
      - 'What are tickets': tickets.md
      - 'How to Make a Ticket Panel': create-panel.md
    - 'Leveling System': 
      - 'How it works': leveling.md
    - 'Suggestions System': 
      - 'How it works': suggestions.md
    - 'Status':
        - 'How to set it up': status.md
    - 'Punishments Integration': punishments-integration.md
    
    
    
extra_css:
  - stylesheets/extra.css


dev_addr: '0.0.0.0:3000'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


